package com.springboot.nacedetail.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.io.Serializable;

@Entity
@Table(name = "NACE_DETAIL")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NaceDetail implements Serializable {

    private static final long serialVersionUID = -1670893016517855654L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @ApiModelProperty(value = "autogenerated id")
    private Long id;

    @Size(min = 3, max = 20, message = "Please enter a valid order no")
    @Pattern(message = "Order Number must be a number", regexp="^[0-9]*$")
    @Column(name = "N_ORDER", unique = true, nullable = false, length = 10)
    @NotBlank(message = "Order number cannot be null or empty")
    private String naceOrderNumber;

    @ApiModelProperty(value = "this is the nace-details level")
    @Min(value = 1, message = "Level must be a positive integer")
    private Integer level;

    @ApiModelProperty(value = "this is the nace-details code")
    private String code;

    @ApiModelProperty(value = "this is the nace-details parent")
    private String parent;

    @ApiModelProperty(value = "this is the nace-details description")
    private String description;
}
